//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arebis.QuickQueryBuilder.Providers.MSSql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MSSqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSSqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arebis.QuickQueryBuilder.Providers.MSSql.MSSqlQueries", typeof(MSSqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, IS_NULLABLE FROM [INFORMATION_SCHEMA].[COLUMNS]
        ///WHERE TABLE_SCHEMA = @Schema AND TABLE_NAME = @Table
        ///ORDER BY 1.
        /// </summary>
        internal static string RetrieveColumns {
            get {
                return ResourceManager.GetString("RetrieveColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select user + &apos;@&apos; + @@servername.
        /// </summary>
        internal static string RetrieveConnectionName {
            get {
                return ResourceManager.GetString("RetrieveConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///   CONCAT(OBJECT_SCHEMA_NAME(fk.parent_object_id), &apos;.&apos;, OBJECT_NAME(fk.parent_object_id), &apos; via (&apos;, OBJECT_SCHEMA_NAME(fk.parent_object_id), &apos;.&apos;, fk.name, &apos;)&apos;) AS RELATION_NAME,
        ///   DB_NAME() AS CONSTRAINT_CATALOG,
        ///   OBJECT_SCHEMA_NAME(fk.object_id) + &apos;.&apos; + fk.name AS CONSTRAINT_NAME,
        ///   DB_NAME() AS TABLE_CATALOG,
        ///   OBJECT_SCHEMA_NAME(fk.parent_object_id) + &apos;.&apos; + OBJECT_NAME(fk.parent_object_id) AS TABLE_NAME,
        ///   fkcl.name AS COLUMN_NAME,
        ///   fkc.constraint_column_id AS ORDINAL_POSITION,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveRelations {
            get {
                return ResourceManager.GetString("RetrieveRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///   CONCAT(OBJECT_SCHEMA_NAME(fk.referenced_object_id), &apos;.&apos;, OBJECT_NAME(fk.referenced_object_id), &apos; via (&apos;, OBJECT_SCHEMA_NAME(fk.parent_object_id), &apos;.&apos;, fk.name, &apos;)&apos;) AS RELATION_NAME,
        ///   DB_NAME() AS CONSTRAINT_CATALOG,
        ///   OBJECT_SCHEMA_NAME(fk.object_id) + &apos;.&apos; + fk.name AS CONSTRAINT_NAME,
        ///   DB_NAME() AS TABLE_CATALOG,
        ///   OBJECT_SCHEMA_NAME(fk.parent_object_id) + &apos;.&apos; + OBJECT_NAME(fk.parent_object_id) AS TABLE_NAME,
        ///   fkcl.name AS COLUMN_NAME,
        ///   fkc.constraint_column_id AS ORDINAL_POSIT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveReverseRelations {
            get {
                return ResourceManager.GetString("RetrieveReverseRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT NAME FROM [MASTER].[SYS].[DATABASES] WHERE HAS_DBACCESS(NAME)=1 ORDER BY 1.
        /// </summary>
        internal static string RetrieveSchemas {
            get {
                return ResourceManager.GetString("RetrieveSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_SCHEMA + &apos;.&apos; + TABLE_NAME, TABLE_TYPE FROM [INFORMATION_SCHEMA].[TABLES] ORDER BY 1.
        /// </summary>
        internal static string RetrieveTables {
            get {
                return ResourceManager.GetString("RetrieveTables", resourceCulture);
            }
        }
    }
}
