//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arebis.QuickQueryBuilder.Providers.Oracle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OracleQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OracleQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arebis.QuickQueryBuilder.Providers.Oracle.OracleQueries", typeof(OracleQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE FROM ALL_TAB_COLS WHERE OWNER=:Owner AND TABLE_NAME=:TableName ORDER BY 1.
        /// </summary>
        internal static string RetrieveColumns {
            get {
                return ResourceManager.GetString("RetrieveColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sys_context(&apos;USERENV&apos;,&apos;SESSION_USER&apos;) || &apos;@&apos; || sys_context(&apos;USERENV&apos;,&apos;DB_NAME&apos;) 
        ///from dual.
        /// </summary>
        internal static string RetrieveConnectionName {
            get {
                return ResourceManager.GetString("RetrieveConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AC.OWNER || &apos;.&apos; || AC.TABLE_NAME || &apos; via &apos; || AC.CONSTRAINT_NAME CONSTRAINT_NAME, AI.TABLE_OWNER ORIGIN_TABLE_OWNER, AI.TABLE_NAME ORIGIN_TABLE_NAME, AIC.COLUMN_NAME ORIGIN_COLUMN_NAME, AIC.COLUMN_POSITION ORIGIN_COLUMN_POSITION, AC.OWNER FOREIGN_TABLE_OWNER, AC.TABLE_NAME FOREIGN_TABLE_NAME, ACC.COLUMN_NAME FOREIGN_COLUMN_NAME, ACC.POSITION FOREIGN_COLUMN_POSITION
        ///FROM ALL_CONSTRAINTS AC,
        ///     ALL_CONS_COLUMNS ACC,
        ///     ALL_INDEXES AI,
        ///     ALL_IND_COLUMNS AIC
        ///WHERE AC.OWNER = ACC.OWNER AND AC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveRelations {
            get {
                return ResourceManager.GetString("RetrieveRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT AI.TABLE_OWNER || &apos;.&apos; || AI.TABLE_NAME || &apos; via &apos; || AC.CONSTRAINT_NAME CONSTRAINT_NAME, AI.TABLE_OWNER ORIGIN_TABLE_OWNER, AI.TABLE_NAME ORIGIN_TABLE_NAME, AIC.COLUMN_NAME ORIGIN_COLUMN_NAME, AIC.COLUMN_POSITION ORIGIN_COLUMN_POSITION, AC.OWNER FOREIGN_TABLE_OWNER, AC.TABLE_NAME FOREIGN_TABLE_NAME, ACC.COLUMN_NAME FOREIGN_COLUMN_NAME, ACC.POSITION FOREIGN_COLUMN_POSITION
        ///FROM ALL_CONSTRAINTS AC,
        ///     ALL_CONS_COLUMNS ACC,
        ///     ALL_INDEXES AI,
        ///     ALL_IND_COLUMNS AIC
        ///WHERE AC.OWNER = ACC.OWNER  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetrieveReverseRelations {
            get {
                return ResourceManager.GetString("RetrieveReverseRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT OWNER FROM ALL_TABLES
        ///UNION
        ///SELECT DISTINCT OWNER FROM ALL_VIEWS
        ///ORDER BY 1.
        /// </summary>
        internal static string RetrieveSchemas {
            get {
                return ResourceManager.GetString("RetrieveSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_NAME, &apos;TABLE&apos; OBJECT_TYPE FROM ALL_TABLES WHERE OWNER=:Owner
        ///UNION
        ///SELECT VIEW_NAME, &apos;VIEW&apos; FROM ALL_VIEWS WHERE OWNER=:Owner
        ///ORDER BY 1.
        /// </summary>
        internal static string RetrieveTables {
            get {
                return ResourceManager.GetString("RetrieveTables", resourceCulture);
            }
        }
    }
}
